nohup ./naif_xp_papi_langnat Textes/shakespeare.txt 200 > resultats_papi_langnat/naif_xp_papi_langnat_shakespeare_200.txt &
nohup ./kmp_papi_langnat Textes/shakespeare.txt 200 > resultats_papi_langnat/kmp_papi_langnat_shakespeare_200.txt &
nohup ./kmp2_papi_langnat Textes/shakespeare.txt 200 > resultats_papi_langnat/kmp2_papi_langnat_shakespeare_200.txt &
nohup ./ag_papi_langnat Textes/shakespeare.txt 200 > resultats_papi_langnat/ag_papi_langnat_shakespeare_200.txt &
nohup ./aoso2_papi_langnat Textes/shakespeare.txt 200 > resultats_papi_langnat/aoso2_papi_langnat_shakespeare_200.txt &
nohup ./aoso6_papi_langnat Textes/shakespeare.txt 200 > resultats_papi_langnat/aoso6_papi_langnat_shakespeare_200.txt &
nohup ./bmh-sbndm_papi_langnat Textes/shakespeare.txt 200 > resultats_papi_langnat/bmh-sbndm_papi_langnat_shakespeare_200.txt &
nohup ./bndmq4_papi_langnat Textes/shakespeare.txt 200 > resultats_papi_langnat/bndmq4_papi_langnat_shakespeare_200.txt &
nohup ./ebom_papi_langnat Textes/shakespeare.txt 200 > resultats_papi_langnat/ebom_papi_langnat_shakespeare_200.txt &
nohup ./fjs_papi_langnat Textes/shakespeare.txt 200 > resultats_papi_langnat/fjs_papi_langnat_shakespeare_200.txt &
nohup ./fs_papi_langnat Textes/shakespeare.txt 200 > resultats_papi_langnat/fs_papi_langnat_shakespeare_200.txt &
nohup ./fsbndm_papi_langnat Textes/shakespeare.txt 200 > resultats_papi_langnat/fsbndm_papi_langnat_shakespeare_200.txt &
nohup ./graspm_papi_langnat Textes/shakespeare.txt 200 > resultats_papi_langnat/graspm_papi_langnat_shakespeare_200.txt &
nohup ./hash3_papi_langnat Textes/shakespeare.txt 200 > resultats_papi_langnat/hash3_papi_langnat_shakespeare_200.txt &
nohup ./hash5_papi_langnat Textes/shakespeare.txt 200 > resultats_papi_langnat/hash5_papi_langnat_shakespeare_200.txt &
nohup ./hash8_papi_langnat Textes/shakespeare.txt 200 > resultats_papi_langnat/hash8_papi_langnat_shakespeare_200.txt &
nohup ./kbndm_papi_langnat Textes/shakespeare.txt 200 > resultats_papi_langnat/kbndm_papi_langnat_shakespeare_200.txt &
nohup ./lbndm_papi_langnat Textes/shakespeare.txt 200 > resultats_papi_langnat/lbndm_papi_langnat_shakespeare_200.txt &
nohup ./sa_papi_langnat Textes/shakespeare.txt 200 > resultats_papi_langnat/sa_papi_langnat_shakespeare_200.txt &
nohup ./sbndm-bmh_papi_langnat Textes/shakespeare.txt 200 > resultats_papi_langnat/sbndm-bmh_papi_langnat_shakespeare_200.txt &
nohup ./sbndmq4_papi_langnat Textes/shakespeare.txt 200 > resultats_papi_langnat/sbndmq4_papi_langnat_shakespeare_200.txt &
nohup ./ssef_papi_langnat Textes/shakespeare.txt 200 > resultats_papi_langnat/ssef_papi_langnat_shakespeare_200.txt &
nohup ./tunedbm_papi_langnat Textes/shakespeare.txt 200 > resultats_papi_langnat/tunedbm_papi_langnat_shakespeare_200.txt &
nohup ./tvsbs_papi_langnat Textes/shakespeare.txt 200 > resultats_papi_langnat/tvsbs_papi_langnat_shakespeare_200.txt &