nohup ./naif_xp_langnat Textes/bible.txt 200 > resultats_langnat/naif_xp_langnat_bible_200.txt &
nohup ./kmp_langnat Textes/bible.txt 200 > resultats_langnat/kmp_langnat_bible_200.txt &
nohup ./kmp2_langnat Textes/bible.txt 200 > resultats_langnat/kmp2_langnat_bible_200.txt &
nohup ./ag_langnat Textes/bible.txt 200 > resultats_langnat/ag_langnat_bible_200.txt &
nohup ./aoso2_langnat Textes/bible.txt 200 > resultats_langnat/aoso2_langnat_bible_200.txt &
nohup ./aoso6_langnat Textes/bible.txt 200 > resultats_langnat/aoso6_langnat_bible_200.txt &
nohup ./bmh-sbndm_langnat Textes/bible.txt 200 > resultats_langnat/bmh-sbndm_langnat_bible_200.txt &
nohup ./bndmq4_langnat Textes/bible.txt 200 > resultats_langnat/bndmq4_langnat_bible_200.txt &
nohup ./ebom_langnat Textes/bible.txt 200 > resultats_langnat/ebom_langnat_bible_200.txt &
nohup ./fjs_langnat Textes/bible.txt 200 > resultats_langnat/fjs_langnat_bible_200.txt &
nohup ./fs_langnat Textes/bible.txt 200 > resultats_langnat/fs_langnat_bible_200.txt &
nohup ./fsbndm_langnat Textes/bible.txt 200 > resultats_langnat/fsbndm_langnat_bible_200.txt &
nohup ./graspm_langnat Textes/bible.txt 200 > resultats_langnat/graspm_langnat_bible_200.txt &
nohup ./hash3_langnat Textes/bible.txt 200 > resultats_langnat/hash3_langnat_bible_200.txt &
nohup ./hash5_langnat Textes/bible.txt 200 > resultats_langnat/hash5_langnat_bible_200.txt &
nohup ./hash8_langnat Textes/bible.txt 200 > resultats_langnat/hash8_langnat_bible_200.txt &
nohup ./kbndm_langnat Textes/bible.txt 200 > resultats_langnat/kbndm_langnat_bible_200.txt &
nohup ./lbndm_langnat Textes/bible.txt 200 > resultats_langnat/lbndm_langnat_bible_200.txt &
nohup ./sa_langnat Textes/bible.txt 200 > resultats_langnat/sa_langnat_bible_200.txt &
nohup ./sbndm-bmh_langnat Textes/bible.txt 200 > resultats_langnat/sbndm-bmh_langnat_bible_200.txt &
nohup ./sbndmq4_langnat Textes/bible.txt 200 > resultats_langnat/sbndmq4_langnat_bible_200.txt &
nohup ./ssef_langnat Textes/bible.txt 200 > resultats_langnat/ssef_langnat_bible_200.txt &
nohup ./tunedbm_langnat Textes/bible.txt 200 > resultats_langnat/tunedbm_langnat_bible_200.txt &
nohup ./tvsbs_langnat Textes/bible.txt 200 > resultats_langnat/tvsbs_langnat_bible_200.txt &